### ISSUE TITLE
document format nog recognised for PDF, DOCX

### ISSUE THREAD

**Issue by oxitech239** [linuxfoundation/cii-census#17]
Thanks for this initiative, i'm a bit stumped the documents for PDF and DOCX return errors on an unrecognised format. I'm sure this knows a benign origin but for now i rest in a mild panic.

**Comment by skhakimov** [comment]
Hello,

I am able to open DOCS and PDF with no issues, including within a browser.  What system are you using?
Just tried with Libre Office on Mac OS X and Open Office on Windows 7 and it opens without errors.

PDF can also be obtained from https://www.coreinfrastructure.org/sites/cii/files/pages/files/pub_ida_lf_cii_070915.pdf

**Comment by oxitech239** [comment]
Hi,

Using a windows system, the in-browser github pdf to image rendering works fine. I want a copy for offline reading so thank for the link.

Using official software for MS Office and Adobe Acrobat to no avail. I assume these documents were generated from LibreOffice or similar.


----- Oorspronkelijk bericht -----
Van: Sam Khakimov <notifications@github.com>
Aan: linuxfoundation/cii-census <cii-census@noreply.github.com>
Cc: oxitech239 <oxitech@telenet.be>
Verzonden: Tue, 14 Jul 2015 17:00:32 +0200 (CEST)
Onderwerp: Re: [cii-census] document format nog recognised for PDF, DOCX (#17)

Hello,

I am able to open DOCS and PDF with no issues, including within a browser.  What system are you using?
Just tried with Libre Office on Mac OS X and Open Office on Windows 7 and it opens without errors.

PDF can also be obtained from https://www.coreinfrastructure.org/sites/cii/files/pages/files/pub_ida_lf_cii_070915.pdf

---

**Comment by skhakimov** [comment]
Yes - they were generated using LibreOffice.  I tried opening PDF with Adobe Reader X on Windows 7 and it worked fine.  Another option is to click on Raw and open within a browser (e.g. Chrome)

**Comment by oxitech239** [comment]
Sorry, i cannot agree this works 'fine'. None of the documents can be opened, not with Acrobat, not with MS office. I'm not interested in online reading, i want an offline version which i can read.

**Comment by oxitech239** [comment]
Downloaded the .zip file, worked fine, thanks anyway.
